version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.local
      args:
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HAFFA_BACKEND_URL=http://localhost:3000
    ports:
      - '4000:4000'
    restart: always
